### ISSUE TITLE
Exception occurs with thrift=0.10.0

### ISSUE THREAD

**Issue by tossmilestone** [prezi/django-zipkin#11]
If run with thrift=0.10.0，the exception will raised on building the span:
```
[2017-04-21,16:15:41]<ERROR>[root]ZipkinMiddleware.process_response failed[process_response:113]
Traceback (most recent call last):
  File "django-zipkin/django_zipkin/middleware.py", line 110, in process_response
    self.logger.info(self.api.build_log_message())
  File "django-zipkin/django_zipkin/api.py", line 38, in build_log_message
    self._build_span().write(protocol)
  File "django-zipkin/django_zipkin/_thrift/zipkinCore/ttypes.py", line 424, in write
    oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
TypeError: expecting tuple of size 3 for list/set type args

```
Thrift=0.9.3 works well. I think the requirement in setup.py must add the limit 'thrift<0.10.0'.

**Comment by tossmilestone** [comment]
This project seems not to be maintained any more, I will close this issue then.
