### ISSUE TITLE
Add more detailed documentation or example on configuration

### ISSUE THREAD

**Issue by txels** [prezi/django-zipkin#4]
The current documentation mentions *From here you it’s up to you to get the messages to Zipkin.* - it then goes on to describe in generic terms what you people at Prezi do. But it is not clear to me at all how to configure logging to "send to the local Scribe instance". Can you add an example of logging configuration? Do you use a custom logger that is not part of this repo? What do you use as formatter?

E.g. I can easily set up django-zipkin to log into a file, crude base64-encoded thrift messages.

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'standard': {
            'format': '%(asctime)s - %(levelname)s - %(name)s - %(filename)s:%(funcName)s:%(lineno)d - %(message)s'
        },
    },
    'handlers': {
        ...
        'zipkin_log': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(os.environ['LOGS_DIR'], 'zipkin.log'),
        },
    },
    'loggers': {
        ...
        'zipkin': {
            'level': 'DEBUG',
            'handlers': ['zipkin_log'],
            'propagate': False,
        },
    }
}
```

This generates log entries that look correct, but of course in a file:

```
CgABe48NUzpEGdYLAAMAAAADR0VUCgAE1b2L2yUKDLwPAAYMAAAAAgoAAQAFGCuTd6kaCwACAAAAAnNyDAADCAABfwAAAQsAAwAAAAN3ZWIAAAoAAQAFGCuTeCOECwACAAAAAnNzDAADCAABfwAAAQsAAwAAAAN3ZWIAAA8ACAwAAAAGCwABAAAACGh0dHAudXJpCwACAAAACC9qc2kxOG4vCAADAAAABgwABAgAAX8AAAELAAMAAAADd2ViAAALAAEAAAAPZGphbmdvLnVybF9uYW1lCwACAAAAB2pzLWkxOG4IAAMAAAAGDAAECAABfwAAAQsAAwAAAAN3ZWIAAAsAAQAAABVkamFuZ28udmlldy5mdW5jX25hbWULAAIAAAASamF2YXNjcmlwdF9jYXRhbG9nCAADAAAABgwABAgAAX8AAAELAAMAAAADd2ViAAALAAEAAAAQZGphbmdvLnZpZXcuYXJncwsAAgAAAAJbXQgAAwAAAAYMAAQIAAF/AAABCwADAAAAA3dlYgAACwABAAAAEmRqYW5nby52aWV3Lmt3YXJncwsAAgAAACl7InBhY2thZ2VzIjogWyJjb3JlMi51aSIsICJkamFuZ28uY29uZiJdfQgAAwAAAAYMAAQIAAF/AAABCwADAAAAA3dlYgAACwABAAAAD2h0dHAuc3RhdHVzY29kZQsAAgAAAAgAAAAAAAAAyAgAAwAAAAQMAAQIAAF/AAABCwADAAAAA3dlYgAAAgAJAAA=
```

But I'm a bit stuck after that. Happy to contribute a PR later with more polished documentation if you give me the right pointers.

**Comment by zsol** [comment]
Essentially you'll need to create a subclass of `logging.Handler` that makes sure everything you `emit()` gets sent to the host/port zipkin's scribe interface listens on. 

At Prezi we run an instance of scribe on every machine and they are configured to forward these logs to zipkin's scribe interface, so that's what "local Scribe instance" refers to.

Hope that clears it up

**Comment by txels** [comment]
Thanks for the quick reply.

Yes that sounds like the thing to do, I'll fight with the specifics of how to write that properly. I was secretly hoping you'd post some actual code sample :)

ATM, since you already have generated thrift code within this library, I'm trying to write such a logger based on those. I wonder whether you have any objection about including such a logger in django-zipkin, and what made you decide not to.

**Comment by zsol** [comment]
The reason we're not very explicit about the details is that part of our infrastructure is not opensource, but here are a couple of pointers:

```python

from scribe import scribe # this is the thrift-generated python library for scribe
class ScribeLogHandler(logging.Handler):
    def __init__(self, category=None):
       protocol = ... #some thrift boilerplate here
       self.client = scribe.Client(iprot=protocol, oprot=protocol)
    def emit(self, record):
        now = datetime.datetime.now()
        record.servertime = "%s,%0.3d" % (now.strftime("%Y-%m-%d %H:%M:%S"), now.microsecond / 1000)
        message = "\\n".join([r for r in self.format(record).split("\n") if r != ""]) + "\n"
        try:
            self.client.Log(scribe.LogEntry(category=self.category, message=message))
        except Exception:
            self.handleError(message)
```

**Comment by txels** [comment]
Thanks a lot for your help!

I got somewhere.

For now I'm playing in ipython. I managed to send a django-zipkin generated message all the way down to zipkin. It looks like the message is malformed though:

The message (b64):

```
CgABEguoD8y+59ELAAMAAAADR0VUCgAETctQERdKvMcPAAYMAAAAAgoAAQAFGDwjL+6KCwACAAAAAnNyDAADCAABfwAAAQsAAwAAAAN3ZWIAAAoAAQAFGDwjM1yPCwACAAAAAnNzDAADCAABfwAAAQsAAwAAAAN3ZWIAAA8ACAwAAAAGCwABAAAACGh0dHAudXJpCwACAAAAMy9kb2MvZjQwZjE1NzQtMGVhZi0xMWU1LThlNzEtNmM0MDA4OTFhNTRjL3Byb2plY3RzLwgAAwAAAAYMAAQIAAF/AAABCwADAAAAA3dlYgAACwABAAAAD2RqYW5nby51cmxfbmFtZQsAAgAAAANkb2MIAAMAAAAGDAAECAABfwAAAQsAAwAAAAN3ZWIAAAsAAQAAABVkamFuZ28udmlldy5mdW5jX25hbWULAAIAAAAMdmlld19mb3JfZG9jCAADAAAABgwABAgAAX8AAAELAAMAAAADd2ViAAALAAEAAAAQZGphbmdvLnZpZXcuYXJncwsAAgAAAAJbXQgAAwAAAAYMAAQIAAF/AAABCwADAAAAA3dlYgAACwABAAAAEmRqYW5nby52aWV3Lmt3YXJncwsAAgAAAEh7ImlkIjogImY0MGYxNTc0LTBlYWYtMTFlNS04ZTcxLTZjNDAwODkxYTU0YyIsICJhcmdzdHJpbmciOiAicHJvamVjdHMvIn0IAAMAAAAGDAAECAABfwAAAQsAAwAAAAN3ZWIAAAsAAQAAAA9odHRwLnN0YXR1c2NvZGULAAIAAAAIAAAAAAAAAMgIAAMAAAAEDAAECAABfwAAAQsAAwAAAAN3ZWIAAAIACQAA
```

My code so far:

```
import base64

from thrift.transport import TTransport, TSocket
from thrift.protocol import TBinaryProtocol

from django_zipkin._thrift.scribe import Scribe

def get_connection_data(host, port):
    socket = TSocket.TSocket(host=host, port=port)
    transport = TTransport.TFramedTransport(socket)
    protocol = TBinaryProtocol.TBinaryProtocol(
        trans=transport, strictRead=False, strictWrite=False)
    return transport, protocol


def get_scribe(host, port):
    transport, protocol = get_connection_data(host, port)
    client = Scribe.Client(iprot=protocol, oprot=protocol)
    return transport, client


def to_zipkin(transport, client, log_entry):
    log_entry = base64.decodestring(log_entry)
    transport.open()
    log_entry = Scribe.LogEntry(category='zipkin', message=log_entry)
    result = client.Log(messages=[log_entry])
    transport.close()
    return result
```


```
[error] WAR [20150611-11:30:07.006] processor: Invalid msg:
[error] WAR [20150611-11:30:07.006] processor:
                                               ????
                                                   GET
[error] WAR [20150611-11:30:07.006] processor: M?PJ??

[error] WAR [20150611-11:30:07.006] processor: <#/?
                                                   sr
                                                    
                                                     web
[error] WAR [20150611-11:30:07.006] processor: <#3\?
                                                    ss
                                                     
                                                      web

                                                       http.uri
                                                               3/doc/f40f1574-0eaf-11e5-8e71-6c400891a54c/projects/
                                                                                                                 
                                                                                                                  web
                                                                                                                     django.url_name
              doc
               
                web
                   django.view.func_name

                                        view_for_doc
                                                  
                                                   web
                                                      django.view.args
                                                                      []
                                                                      
                                                                       web
                                                                          django.view.kwargs
                                                                                            H{"id": "f40f1574-0eaf-11e5-8e71-6c400891a54c", "argstring": "projects/"}
                                             
                                              web
                                                 http.statuscode
                                                               ?
                                                              
                                                               web
[error] WAR [20150611-11:30:07.006] processor: scala.MatchError: 24 (of class java.lang.Byte)
[error] WAR [20150611-11:30:07.006] processor:     at com.twitter.scrooge.ThriftUtil$.transfer(ThriftUtil.scala:17)
[error] WAR [20150611-11:30:07.006] processor:     at com.twitter.scrooge.ThriftUtil$.transfer(ThriftUtil.scala:11)
```

**Comment by txels** [comment]
Hey no worries. I just found out that sending that same message to latest zipkin running locally, it's ingested correctly:

```
[error] DEB [20150611-16:07:53.443] processor: Processing span: Span(1300317703239559121,GET,5605662195528154311,None,List(Annotation(1434021451001482,sr,Some(127.0.0.1:0(web)),None), Annotation(1434021451226255,ss,Some(127.0.0.1:0(web)),None)),Vector(BinaryAnnotation(http.uri,java.nio.HeapByteBuffer[pos=0 lim=51 cap=51],AnnotationType(6,String),Some(127.0.0.1:0(web))), BinaryAnnotation(django.url_name,java.nio.HeapByteBuffer[pos=0 lim=3 cap=3],AnnotationType(6,String),Some(127.0.0.1:0(web))), BinaryAnnotation(django.view.func_name,java.nio.HeapByteBuffer[pos=0 lim=12 cap=12],AnnotationType(6,String),Some(127.0.0.1:0(web))), BinaryAnnotation(django.view.args,java.nio.HeapByteBuffer[pos=0 lim=2 cap=2],AnnotationType(6,String),Some(127.0.0.1:0(web))), BinaryAnnotation(django.view.kwargs,java.nio.HeapByteBuffer[pos=0 lim=72 cap=72],AnnotationType(6,String),Some(127.0.0.1:0(web))), BinaryAnnotation(http.statuscode,java.nio.HeapByteBuffer[pos=0 lim=8 cap=8],AnnotationType(4,I64),Some(127.0.0.1:0(web)))),false) from CgABEguoD8y+59ELAAMAAAADR0VUCgAETctQERdKvMcPAAYMAAAAAgoAAQAFGDwjL+6KCwACAAAAAnNyDAADCAABfwAAAQsAAwAAAAN3ZWIAAAoAAQAFGDwjM1yPCwACAAAAAnNzDAADCAABfwAAAQsAAwAAAAN3ZWIAAA8ACAwAAAAGCwABAAAACGh0dHAudXJpCwACAAAAMy9kb2MvZjQwZjE1NzQtMGVhZi0xMWU1LThlNzEtNmM0MDA4OTFhNTRjL3Byb2plY3RzLwgAAwAAAAYMAAQIAAF/AAABCwADAAAAA3dlYgAACwABAAAAD2RqYW5nby51cmxfbmFtZQsAAgAAAANkb2MIAAMAAAAGDAAECAABfwAAAQsAAwAAAAN3ZWIAAAsAAQAAABVkamFuZ28udmlldy5mdW5jX25hbWULAAIAAAAMdmlld19mb3JfZG9jCAADAAAABgwABAgAAX8AAAELAAMAAAADd2ViAAALAAEAAAAQZGphbmdvLnZpZXcuYXJncwsAAgAAAAJbXQgAAwAAAAYMAAQIAAF/AAABCwADAAAAA3dlYgAACwABAAAAEmRqYW5nby52aWV3Lmt3YXJncwsAAgAAAEh7ImlkIjogImY0MGYxNTc0LTBlYWYtMTFlNS04ZTcxLTZjNDAwODkxYTU0YyIsICJhcmdzdHJpbmciOiAicHJvamVjdHMvIn0IAAMAAAAGDAAECAABfwAAAQsAAwAAAAN3ZWIAAAsAAQAAAA9odHRwLnN0YXR1c2NvZGULAAIAAAAIAAAAAAAAAMgIAAMAAAAEDAAECAABfwAAAQsAAwAAAAN3ZWIAAAIACQAA
```

It could be some version incompatibility with the docker images I was using...? https://registry.hub.docker.com/u/itszero/zipkin-collector/ hard for me to tell.

**Comment by zsol** [comment]
That would be my guess as well. If it's working for you, feel free to contribute your code :)

**Comment by txels** [comment]
I wrote a logger but for some reason connecting to local scribe was very slow (maybe because it was running on local boot2docker and not localhost). We've discontinued the zipkin approach for now and are relying more on our current kibana setup, so I don't think I'll be doing more work on finishing this off anytime soon.

This is my logger, for completeness:

```python
import logging
from scribe import Scribe
from thrift.transport import TTransport, TSocket
from thrift.protocol import TBinaryProtocol
import datetime

SCRIBE_HOST, SCRIBE_PORT = 'docker.local', 1463
Collector = Scribe


class ScribeLogHandler(logging.Handler):
    def __init__(self, host, port,  category=None):
        super(ScribeLogHandler, self).__init__()
        socket = TSocket.TSocket(host=host, port=port)
        self.transport = TTransport.TFramedTransport(socket)
        protocol = TBinaryProtocol.TBinaryProtocol(
            trans=self.transport, strictRead=False, strictWrite=False)
        self.client = Collector.Client(iprot=protocol, oprot=protocol)
        self.category = category

    def emit(self, record):
        now = datetime.datetime.now()
        record.servertime = "%s,%0.3d" % (
            now.strftime("%Y-%m-%d %H:%M:%S"), now.microsecond / 1000
        )
        message = "\\n".join([r for r in self.format(record).split("\n") if r != ""]) + "\n"
        try:
            self.transport.open()
            entry = Scribe.LogEntry(category=self.category, message=message)
            self.client.Log([entry])
            self.transport.close()
        except Exception as e:
            self.handleError(message)
```

**Comment by abesto** [comment]
Thanks for sharing! I'm sorry to hear zipkin didn't work out for you. We'll be sure to integrate the handler the next time we work on `django-zipkin`.
